//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerRecords.DAL.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CUSTOMEREntitiesConnectionString : DbContext
    {
        public CUSTOMEREntitiesConnectionString()
            : base("name=CUSTOMEREntitiesConnectionString")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CUSTOMER_DETAILS> CUSTOMER_DETAILS { get; set; }
    
        public virtual ObjectResult<GET_ALL_CUSTOMERS_Result> GET_ALL_CUSTOMERS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_ALL_CUSTOMERS_Result>("GET_ALL_CUSTOMERS");
        }
    }
}
